name: "Build"

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup 'go'
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Make
        run: make

  codeql:
    name: CodeQL
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup 'go'
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "go"

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v2
