name: "Build"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest

    env:
      CODEQL_EXTRACTOR_GO_BUILD_TRACING: 'on'

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup 'go'
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "go"

      - name: Build code
        run: make

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v2
